import localFont from "next/font/local";
import "./globals.css";
import "@/public/css/pattern.css"
import { Toaster } from "sonner";
import { ApolloProvider } from "@apollo/client";
import client from "@/lib/apolloClient";
import ApolloProviderWrappper from "@/components/ApolloProviderWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloProviderWrappper >
          {children}
          <Toaster richColors closeButton expand={true} duration={3000} position="top-center" S />
        </ApolloProviderWrappper>
      </body>
    </html>
  );
}
